### ISSUE TITLE
phaser editor shows empty workbench

### ISSUE THREAD

**Issue by atesin** [PhaserEditor2D/PhaserEditor2D-v3#269]
![image](https://user-images.githubusercontent.com/8086106/220794073-2a56f245-0b61-45f6-ba1d-b7138f9ede2f.png)

this is after loading any project... though they seem to run (click the "play" triangle button")

## Version
* Phaser Editor 2D Version: PhaserEditor2D-allInOne-3.36.2-windows.zip
* Operating System: windows 8.1 x64
* Web Browser and version: i am using the all in one version.. but i have many browsers installed, vivaldi, firefox, brave, more

## Description

workbench views empty after loading any project... until projects seem to run but i feel blind (see screenshot above), it doesn't respond to right-click, some hidden menu, run as administrator, etc ... i dont know how to make them visible, i can't even make the tutorials :(

## Possible solution

no idea... does this app run with java?, because i have openjdk 8 installed (don't like big greedy companies like oracle or microsoft, google, etc)...  i am available to contact and do some tests

... if this is a known issue please post it easily accesible in documentation "for future generations", thanks

**Comment by PhaserEditor2D** [comment]
Hi @atesin 

What project template are you using for creating the new project?

Please, can you check if there is an error in the DevTools? You can press Ctrl+Shift+I.

Also, please, try opening the editor in the Terminal, and tell me if you see any error there.

**Comment by PhaserEditor2D** [comment]
>no idea... does this app run with java?

No, it doesn't require Java. It is based on ElectronJS.

Btw, please, can you check your Antivirus quarantine? The electron app opens in the background the backend of the editor, which is the `PhaserEditor2D.exe` file. It is a webserver and maybe the antivirus in intercepting the communication between the server and the app.

**Comment by atesin** [comment]
hi...  i disabled my antivirus (security essentials) and my firewall (windows bundle) and open the app ...  same result

**Comment by PhaserEditor2D** [comment]
> is there any chance to enable some log?

Yes, please, open the editor in the CMD window, and tell me what it prints. Also, you can open the DevTools of the editor (is the same of Chromium because it is ElectronJS) and tell me what ir prints there.

**Comment by atesin** [comment]
remarks:
- something weird happen with ansi color escapes, they are not interpreted (i use ConEmu)
- something odd happen with redirection... sending stdout to a file just logs some messages

command: `PhaserEditor2D-allInOne.exe > phasereditor.log`, then i close the application and logs 3 last lines, the log file shows:
```

Starting Phaser Editor 2D Core server
Saved port: 3576
Spawn: C:\PROGRAMS\PhaserEditor2D-allInOne\resources\app\server\PhaserEditor2D.exe
[
  '-disable-open-browser',
  '-port',
  '3576',
  '-project',
  'C:/PROGRAMS/phaser-projects/new-01'
]
Process ID: 2708
Phaser Editor 2D - v3.36.2

=> Running in Free mode ([31m[1monly 200 files per project allowed[0m[0m)
[31m=> Purchase a license: https://gum.co/phasereditor[0m


[94mStart online    : https://phasereditor2d.com/start[0m
[94mDocumentation   : https://help.phasereditor2d.com/v3[0m
[94mFile bugs/ideas : https://github.com/PhaserEditor2D/PhaserEditor2D-v3/[0m
[94mKeep in contact : https://twitter.com/PhaserEditor2D[0m

[32m=> Open the web browser at [0m[33mhttp://127.0.0.1:3576/editor
[0m
Checking for updates...
Kill server proc 2708
Main process exit. Kill server proc (2708). Exit code (0).
Kill server process 2708
```


command: `PhaserEditor2D-allInOne.exe`, this is copied from console window while program still running, note there are lot more messages:
```
C:\PROGRAMS\PhaserEditor2D-allInOne> PhaserEditor2D-allInOne.exe

C:\PROGRAMS\PhaserEditor2D-allInOne>
Starting Phaser Editor 2D Core server
Saved port: 3576
Spawn: C:\PROGRAMS\PhaserEditor2D-allInOne\resources\app\server\PhaserEditor2D.exe
[
  '-disable-open-browser',
  '-port',
  '3576',
  '-project',
  'C:/PROGRAMS/phaser-projects/new-01'
]
Process ID: 1768
(node:6440) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'setMenu')
    at C:\PROGRAMS\PhaserEditor2D-allInOne\resources\app\src\js\main.js:18:29
(Use `PhaserEditor2D-allInOne --trace-warnings ...` to show where the warning was created)
(node:6440) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
2023/02/27 18:04:30 Scanning user home flags: C:\Users\atesin/.phasereditor2d/flags.txt

2023/02/27 18:04:30 Loading project at C:\PROGRAMS\phaser-projects\new-01
Phaser Editor 2D - v3.36.2

=> Running in Free mode (←[31m←[1monly 200 files per project allowed←[0m←[0m)
←[31m=> Purchase a license: https://gum.co/phasereditor←[0m

2023/02/27 18:04:30 Reading project config
2023/02/27 18:04:30 Program flags: [-disable-open-browser, -port, 3576, -project, C:/PROGRAMS/phaser-projects/new-01]
2023/02/27 18:04:30 User plugins: C:\Users\atesin/.phasereditor2d/plugins
2023/02/27 18:04:30 Listening at http://127.0.0.1:3576/editor

←[94mStart online    : https://phasereditor2d.com/start←[0m
←[94mDocumentation   : https://help.phasereditor2d.com/v3←[0m
←[94mFile bugs/ideas : https://github.com/PhaserEditor2D/PhaserEditor2D-v3/←[0m
←[94mKeep in contact : https://twitter.com/PhaserEditor2D←[0m

←[32m=> Open the web browser at ←[0m←[33mhttp://127.0.0.1:3576/editor
←[0m
Checking for updates...
2023/02/27 18:04:31 Plugin: scanning C:\PROGRAMS\PhaserEditor2D-allInOne\resources\app\server/editor/plugins
2023/02/27 18:04:31 Plugin: add 'colibri'
2023/02/27 18:04:31 Plugin: add 'colibri.inspector'
2023/02/27 18:04:31 Plugin: add 'phasereditor2d.allInOne'
2023/02/27 18:04:31 Plugin: add 'phasereditor2d.animations'
2023/02/27 18:04:31 Plugin: add 'phasereditor2d.blocks'
2023/02/27 18:04:31 Plugin: add 'phasereditor2d.code'
2023/02/27 18:04:31 [Error] Plugin: phasereditor2d.code CreateFile C:\PROGRAMS\PhaserEditor2D-allInOne\resources\app\server/editor/plugins/phasereditor2d.code/plugin.json: El sistema no puede encontrar el archivo especificado.
2023/02/27 18:04:31 Plugin: add 'phasereditor2d.codemirror'
2023/02/27 18:04:31 Plugin: add 'phasereditor2d.files'
2023/02/27 18:04:31 Plugin: add 'phasereditor2d.ide'
2023/02/27 18:04:31 Plugin: add 'phasereditor2d.images'
2023/02/27 18:04:31 Plugin: add 'phasereditor2d.outline'
2023/02/27 18:04:31 Plugin: add 'phasereditor2d.pack'
2023/02/27 18:04:31 Plugin: add 'phasereditor2d.phaser'
2023/02/27 18:04:31 Plugin: add 'phasereditor2d.scene'
2023/02/27 18:04:31 Plugin: add 'phasereditor2d.webContentTypes'
2023/02/27 18:04:31 Plugin: scanning C:\Users\atesin/.phasereditor2d/plugins
2023/02/27 18:04:31 No updates available.
```

**Comment by atesin** [comment]
command: `PhaserEditor2D-allInOne.exe --trace-warnings` as suggested above, copied from console while program is running
```
C:\PROGRAMS\PhaserEditor2D-allInOne> PhaserEditor2D-allInOne.exe --trace-warnings

C:\PROGRAMS\PhaserEditor2D-allInOne>
Starting Phaser Editor 2D Core server
Saved port: 3576
Spawn: C:\PROGRAMS\PhaserEditor2D-allInOne\resources\app\server\PhaserEditor2D.exe
[
  '-disable-open-browser',
  '-port',
  '3576',
  '-project',
  'C:/PROGRAMS/phaser-projects/new-01'
]
Process ID: 6112
(node:6488) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'setMenu')
    at C:\PROGRAMS\PhaserEditor2D-allInOne\resources\app\src\js\main.js:18:29
(Use `PhaserEditor2D-allInOne --trace-warnings ...` to show where the warning was created)
(node:6488) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
2023/02/27 18:10:30 Scanning user home flags: C:\Users\atesin/.phasereditor2d/flags.txt

Phaser Editor 2D - v3.36.2

=> Running in Free mode (←[31m←[1monly 200 files per project allowed←[0m←[0m)
2023/02/27 18:10:30 Loading project at C:\PROGRAMS\phaser-projects\new-01
2023/02/27 18:10:30 Reading project config
2023/02/27 18:10:30 Program flags: [-disable-open-browser, -port, 3576, -project, C:/PROGRAMS/phaser-projects/new-01]
2023/02/27 18:10:30 User plugins: C:\Users\atesin/.phasereditor2d/plugins
2023/02/27 18:10:30 Listening at http://127.0.0.1:3576/editor
←[31m=> Purchase a license: https://gum.co/phasereditor←[0m


←[94mStart online    : https://phasereditor2d.com/start←[0m
←[94mDocumentation   : https://help.phasereditor2d.com/v3←[0m
←[94mFile bugs/ideas : https://github.com/PhaserEditor2D/PhaserEditor2D-v3/←[0m
←[94mKeep in contact : https://twitter.com/PhaserEditor2D←[0m

←[32m=> Open the web browser at ←[0m←[33mhttp://127.0.0.1:3576/editor
←[0m
Checking for updates...
2023/02/27 18:10:31 Plugin: scanning C:\PROGRAMS\PhaserEditor2D-allInOne\resources\app\server/editor/plugins
2023/02/27 18:10:31 Plugin: add 'colibri'
2023/02/27 18:10:31 Plugin: add 'colibri.inspector'
2023/02/27 18:10:31 Plugin: add 'phasereditor2d.allInOne'
2023/02/27 18:10:31 Plugin: add 'phasereditor2d.animations'
2023/02/27 18:10:31 Plugin: add 'phasereditor2d.blocks'
2023/02/27 18:10:31 Plugin: add 'phasereditor2d.code'
2023/02/27 18:10:31 [Error] Plugin: phasereditor2d.code CreateFile C:\PROGRAMS\PhaserEditor2D-allInOne\resources\app\server/editor/plugins/phasereditor2d.code/plugin.json: El sistema no puede encontrar el archivo especificado.
2023/02/27 18:10:31 Plugin: add 'phasereditor2d.codemirror'
2023/02/27 18:10:31 Plugin: add 'phasereditor2d.files'
2023/02/27 18:10:31 Plugin: add 'phasereditor2d.ide'
2023/02/27 18:10:31 Plugin: add 'phasereditor2d.images'
2023/02/27 18:10:31 Plugin: add 'phasereditor2d.outline'
2023/02/27 18:10:31 Plugin: add 'phasereditor2d.pack'
2023/02/27 18:10:31 Plugin: add 'phasereditor2d.phaser'
2023/02/27 18:10:31 Plugin: add 'phasereditor2d.scene'
2023/02/27 18:10:31 Plugin: add 'phasereditor2d.webContentTypes'
2023/02/27 18:10:31 Plugin: scanning C:\Users\atesin/.phasereditor2d/plugins
2023/02/27 18:10:31 No updates available.
```

**Comment by arianfornaris** [comment]
Hi

This error:

> (node:6440) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'setMenu')
    at C:\PROGRAMS\PhaserEditor2D-allInOne\resources\app\src\js\main.js:18:29

I think is related to Windows 8 not supporting the dock menu API. Actually, I found [Electron is removing support for Windows 8](https://www.electronjs.org/blog/windows-7-to-8-1-deprecation-notice).

In any case, I don't think that error is the reason for the empty workspace.

This error:

> 2023/02/27 18:04:31 [Error] Plugin: phasereditor2d.code CreateFile C:\PROGRAMS\PhaserEditor2D-allInOne\resources\app\server/editor/plugins/phasereditor2d.code/plugin.json: El sistema no puede encontrar el archivo especificado.

I don't know why you get that error. The `phasereditor2d.code` plugin was removed from the editor some time ago. Do you have any custom configuration of the editor?

**Comment by atesin** [comment]
> I don't know why you get that error. The `phasereditor2d.code` plugin was removed from the editor some time ago. Do you have any custom configuration of the editor?

not at all...  never knew/tried phasereditor2d before.... i just downloaded from official site, decompress and run

i would like to learn to code some basic 2d run-everywhere games, and i feel intimidated by unreal/unity/godot... i tried phaser before but has to write too many code by hand, develompent feels slow and tedious... i dreamed with some phaser ide

i won't install windows10 soon (actually i wished to stay with windows7 but wanted to use miracast)... do you want i make some tests?

**Comment by PhaserEditor2D** [comment]
Yes please, help me to find the problem.

Please, can you send me a ZIP of the project you are opening? I want to open it here on my pc.

**Comment by PhaserEditor2D** [comment]
By the way, is `assets` the root of your project? Usually, the `assets` folder isn't the root of the project.

**Comment by atesin** [comment]
i dont think one of my projects has a problem....  ANY project i create or open shows this problem, even the "new project" > "basic javascript".... just created, and the views are empty....  so i think chances are problem is from program itself

i dont know how to see what is the root of the project (any project) because it show no folders, no tree, no properties, i feel blind....  i would like if you could guide me to achieve things you are ask me for... sorry for the inconveniences

**Comment by PhaserEditor2D** [comment]
Hi!

When you create a project with All in One, it creates a folder in your file system. The dialog asks you for a location for your project. Please, ZIP that folder created by the editor and attach it here. What I need to know is if the editor is failing on creating the files or opening the files.

**Comment by atesin** [comment]
here is --> [new.zip](https://github.com/PhaserEditor2D/PhaserEditor2D-v3/files/10937177/new.zip)
tell me if you need anything else

**Comment by MercurialUroboros** [comment]
Any update on this? I have the same exact issue on windows. I used the webpack/typescript template.
Using the latest Phaser Editor 2D v3.65.0

**Comment by PhaserEditor2D** [comment]
Hi @MercurialUroboros. Please, can you provide me with your project files?

**Comment by MercurialUroboros** [comment]
[test.zip](https://github.com/PhaserEditor2D/PhaserEditor2D-v3/files/13788236/test.zip)

There you go.

**Comment by PhaserEditor2D** [comment]
Thanks @MercurialUroboros.  I tested it and it works for me. Do you get any error messages?
Can you try another template, like the basic JavaScript project template? Please, check the folder where you are creating the project is empty.

**Comment by PhaserEditor2D** [comment]
The one provided by @atesin works for me too.

**Comment by MercurialUroboros** [comment]
I'm currently on my Mac now, I can't test on windows, and I have the same exact issue.

I'm not sure if i'm doing anything wrong at this point.

<img width="1516" alt="image" src="https://github.com/PhaserEditor2D/PhaserEditor2D-v3/assets/22802482/6521184c-6434-47ec-bf01-4df39ef5e9e9">

**Comment by PhaserEditor2D** [comment]
Also, please, try opening the editor in Chrome instead of Safari.

**Comment by MercurialUroboros** [comment]
I am running with Sudo.
Project has node modules.
I did open with Chrome.

Still same result.

**Comment by PhaserEditor2D** [comment]
I think running it with `sudo` is not a good idea. If you installed the dependencies, then run the editor like this:

`npm run editor`

Also you can try the All in One distribution of the editor. It is a desktop app.

**Comment by MercurialUroboros** [comment]
I was trying to use the web one, cause the all in one is not working either.

I think it asked me to setup something the very first time, and since then, everytime i open it it tells me "you have more than 200 files blah blah" which prevents me to do anything. And i'm not sure how to reset this state.

**Comment by PhaserEditor2D** [comment]
> you have more than 200 files blah blah

It shows it because you opened a folder with a lot of files. I can help you fix it. Can you join Discord? https://discord.com/invite/4DdpMMD I can help you in realtime :)

**Comment by MercurialUroboros** [comment]
Few things:

1. If you have wrongly setup the editor like me, you can reset by ` rm -rf /Users/<your-user>/.phasereditor2d`
2. If it looks like it's doing nothing, you need to open a .scene file first.

**Comment by atesin** [comment]
so, what is the resolution?... what is the fix or workaround we must do to make workbenck show something?

**Comment by PhaserEditor2D** [comment]
> so, what is the resolution?... what is the fix or workaround we must do to make workbenck show something?

Hi. Most of the time it is about a "bad setup" of the editor or the projects. I can help you if you still have a blank workspace. Is it the case?

**Comment by atesin** [comment]
yes...  me and others as i see... we never said that we solved the problem doing X thing, nor receive any suggestion or try

**Comment by PhaserEditor2D** [comment]
Hi @atesin. Yeah, I missed this issue and brought it back to me after MercurialUroboros commented on it.

Please, can you join our Discord channel so I can help you better find what's going on in your setup? https://discord.com/invite/4DdpMMD

**Comment by atesin** [comment]
> Hi @atesin. Yeah, I missed this issue and brought it back to me after MercurialUroboros commented on it.
> 
> Please, can you join our Discord channel so I can help you better find what's going on in your setup? https://discord.com/invite/4DdpMMD

joined!

**Comment by atesin** [comment]
well ...  i joined with @PhaserEditor2D in discord, and he showed me what happens ...  apparently was just an "autoexec" shortcut that was missing, but opening it by hand works:

i hope this were documented somewhere / fixed

- files panel > (project folder) > src > scenes > Level.scene

![imagen](https://github.com/PhaserEditor2D/PhaserEditor2D-v3/assets/8086106/0791e7d5-5cd2-4f8d-a73a-a54191b9642b)

**Comment by MercurialUroboros** [comment]
FYI that was literally point number 2 I meant in my comment @atesin

**Comment by PhaserEditor2D** [comment]
Hi guys. I will make the editor open the scene file by default when it opens a new project. Thanks for your contributions!
